---
- hosts: all
  pre_tasks:
    - apt: "name={{ item }}"
      with_items: [
        nginx,
        php5-cli,
        php5-fpm,
        php5-mysql,
        mysql-server
      ]
    - lineinfile: dest=/etc/nginx/sites-enabled/tokopedia.com insertafter="^\tserver_name localhost;$" line="\tinclude /etc/nginx/global.d/*;"
    - service: name=mysql state=running

  roles:
    - phpmyadmin

  vars:
    - phpmyadmin_php_fpm_socket: unix:/var/run/php5-fpm.sock