---
phpmyadmin_php_fpm_socket: php-fpm

phpmyadmin_server_host: localhost
phpmyadmin_server_auth_type: config
phpmyadmin_server_user: root
phpmyadmin_server_password: root

phpmyadmin_custom_template_filename: config.php.j2
